CREATE DATABASE IF NOT EXISTS tabela_bd;
USE tabela_bd;

CREATE TABLE eleitores( 
id INT PRIMARY KEY AUTO_INCREMENT, 
nome VARCHAR(100), 
cpf VARCHAR(100) NOT NULL UNIQUE, 
titulo CHAR(12) NOT NULL UNIQUE,
mesario CHAR(2) NOT NULL, 
chave_de_acesso VARCHAR(50) UNIQUE NOT NULL, 
votou CHAR (2) NOT NULL
); 

CREATE TABLE candidatos(  
Id INT PRIMARY KEY AUTO_INCREMENT, 
Nome VARCHAR(100) NOT NULL, 
Num_votacao INT NOT NULL UNIQUE, 
Partido VARCHAR(10) NOT NULL 
); 

CREATE TABLE votos( 
Id INT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
Candidato INT,  
Datahora DATETIME NOT NULL, 
Protocolo_votacao VARCHAR(20) NOT NULL UNIQUE
); 

ALTER TABLE votos 
ADD FOREIGN KEY (Candidato) REFERENCES candidatos(id); 

ALTER TABLE votos
MODIFY Protocolo_votacao VARCHAR(20) NOT NULL;

ALTER TABLE votos 
MODIFY Candidato INT NOT NULL;


ALTER TABLE eleitores
MODIFY mesario CHAR(1) NOT NULL CHECK (mesario IN ('S', 'N'));

ALTER TABLE eleitores
MODIFY votou CHAR(1) NOT NULL CHECK (votou IN ('S', 'N'));

